version: "3.8"

services:
  # Frontend Development Server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_APP_NAME=Crypto Portfolio Tracker (Dev)
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    networks:
      - crypto-dev-network
    restart: unless-stopped

  # Backend API Development
  backend-dev:
    image: node:18-alpine
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://user:password@db-dev:5432/crypto_portfolio_dev
      - JWT_SECRET=dev-secret-key
    volumes:
      - ../backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev
    networks:
      - crypto-dev-network
    restart: unless-stopped
    depends_on:
      - db-dev

  # PostgreSQL Database Development
  db-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=crypto_portfolio_dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crypto-dev-network
    restart: unless-stopped

  # Redis Cache Development
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - crypto-dev-network
    restart: unless-stopped

networks:
  crypto-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
  redis_dev_data:
